status = [
    "MSRV",
    "Check",
    "Lints",
    "Offline tests (ubuntu-latest)",
    "Offline tests (windows-latest)",
    "Offline tests (macos-latest)",
    "Test on a real server (anonymous) (1.25.8.5663-e071c3d62)",
    "Test on a real server (authenticated free account) (1.25.8.5663-e071c3d62)",
    "Test on a real server (authenticated plexpass account) (1.25.8.5663-e071c3d62)",
]
delete_merged_branches = true
