status = [
    "MSRV",
    "Check",
    "Lints",
    "Offline tests (ubuntu-latest)",
    "Offline tests (windows-latest)",
    "Offline tests (macos-latest)",
    "Test on a real server (anonymous) (1.27.1.5916-6b0e31a64)",
    "Test on a real server (authenticated free account) (1.27.1.5916-6b0e31a64)",
    "Test on a real server (authenticated plexpass account) (1.27.1.5916-6b0e31a64)",
]
delete_merged_branches = true
