status = [
    "MSRV",
    "Check",
    "Lints",
    "Offline tests (ubuntu-latest)",
    "Offline tests (windows-latest)",
    "Offline tests (macos-latest)",
    "Test on a real server (anonymous) (1.26.0.5715-8cf78dab3)",
    "Test on a real server (authenticated free account) (1.26.0.5715-8cf78dab3)",
    "Test on a real server (authenticated plexpass account) (1.26.0.5715-8cf78dab3)",
]
delete_merged_branches = true
