status = [
    "MSRV",
    "Check",
    "Lints",
    "Offline tests (ubuntu-latest)",
    "Offline tests (windows-latest)",
    "Offline tests (macos-latest)",
    "Test on a real server (anonymous) (%",
    "Test on a real server (authenticated free account) (%",
    "Test on a real server (authenticated plexpass account) (%",
]
delete_merged_branches = true
