status = [
    "MSRV",
    "Check",
    "Lints",
    "Offline tests (ubuntu-latest)",
    "Offline tests (windows-latest)",
    "Offline tests (macos-latest)",
    "Test on a real server (anonymous) (1.26.2.5797-5bd057d2b)",
    "Test on a real server (authenticated free account) (1.26.2.5797-5bd057d2b)",
    "Test on a real server (authenticated plexpass account) (1.26.2.5797-5bd057d2b)",
]
delete_merged_branches = true
