status = [
    "MSRV",
    "Check",
    "Lints",
    "Offline tests (ubuntu-latest)",
    "Offline tests (windows-latest)",
    "Offline tests (macos-latest)",
    "Test on a real server (anonymous) (latest)",
    "Test on a real server (authenticated free account) (latest)",
    "Test on a real server (authenticated plexpass account) (latest)",
]
delete_merged_branches = true
