language: rust

cache: cargo

script:
  - cargo test --verbose --all

matrix:
  fast_finish: true

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - rust: stable
    - rust: beta
    - name: "Clippy"
      rust: stable
      before_script:
        - rustup component add clippy
      script:
        - cargo clippy --all-targets --all-features -- -D warnings
    - name: "Format check"
      rust: stable
      before_script:
        - rustup component add rustfmt
      script:
        - cargo fmt -- --check
    - stage: deploy
      name: "Deploy to Cargo"
      rust: stable
      script: skip
      deploy:
        - provider: script
          script: rm -rf target && cd plex-api && cargo publish --token $CARGO_TOKEN
          on:
            tags: true
            repo: andrey-yantsen/plex-api.rs
