[package]
name = "plex-api"
version = "0.0.0"
authors = ["Andrey Yantsen <andrey@janzen.su>"]
edition = "2018"
description = "Library for communication with Plex server"
license = "MIT"
repository = "https://github.com/andrey-yantsen/plex-api.rs"

[dependencies]
