[package]
name = "plex-api"
version = "0.0.0"
authors = ["Andrey Yantsen <andrey@janzen.su>"]
edition = "2018"
description = "Library for communication with Plex server"
license = "MIT"
repository = "https://github.com/andrey-yantsen/plex-api.rs"

[dependencies]
reqwest = "0.9.8"
uname = "0.1.1"
uuid = "0.7.1"
log = "0.4.6"
serde = "1.0.84"
serde_derive = "1.0.84"
serde_json = "1.0.35"
serde-xml-rs = "0.3.0"
serde_with = "0.2.5"
