[package]
name = "plex-cli"
version = "0.1.0"
authors = ["Andrey Yantsen <andrey@janzen.su>"]
edition = "2018"

[dependencies]
plex-api = { path = "../plex-api" }
log = "0.4"
fern = "0.5"
chrono = "0.4.6"
async-std = "0.99"
tokio = { version = "0.2", features = ["macros"] }
