[package]
name = "plex-cli"
version = "0.1.1"
authors = ["Andrey Yantsen <andrey@janzen.su>"]
edition = "2018"

[dependencies]
plex-api = { path = "../plex-api" }
log = "0.4"
fern = "0.5"
chrono = "0.4"
tokio = { version = "0.2", features = ["macros"] }
clap = { version = "2.33", features = ["yaml"] }
async-std = { version = "1.4", features = ["unstable"] }
thiserror = "1.0"
