---
"on":
  push:
    branches: [main]

name: release-please
jobs:
  release-please-plex-api:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          path: "crates/plex-api"
          package-name: plex-api
          release-type: rust
          monorepo-tags: true
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          release-as: '0.0.5'
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"chore","section":"Miscellaneous","hidden":false},
             {"type":"test","section":"Tests","hidden":true},
             {"type":"ci","section":"Continuous Integration","hidden":true},
             {"type":"docs","section":"Documentation","hidden":true},
             {"type":"refactor","section":"Code Refactoring","hidden":true},
             {"type":"style","section":"Styles","hidden":true}]

      # The logic below handles the crates.io publication:
      - name: Checkout sources
        uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: steps.release.outputs.release_created
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
        if: steps.release.outputs.release_created
      - run: cargo publish -p plex-api
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CRATES_IO_TOKEN }}"
        if: steps.release.outputs.release_created

  release-please-plex-cli:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          path: "crates/plex-cli"
          package-name: plex-cli
          release-type: rust
          monorepo-tags: true
          bump-minor-pre-major: true
          bump-patch-for-minor-pre-major: true
          release-as: '0.0.2'
          changelog-types: |
            [{"type":"feat","section":"Features","hidden":false},
             {"type":"fix","section":"Bug Fixes","hidden":false},
             {"type":"chore","section":"Miscellaneous","hidden":false},
             {"type":"test","section":"Tests","hidden":true},
             {"type":"ci","section":"Continuous Integration","hidden":true},
             {"type":"docs","section":"Documentation","hidden":true},
             {"type":"refactor","section":"Code Refactoring","hidden":true},
             {"type":"style","section":"Styles","hidden":true}]

      # The logic below handles the crates.io publication:
      - name: Checkout sources
        uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: steps.release.outputs.release_created
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
        if: steps.release.outputs.release_created
      - run: cargo publish -p plex-cli
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CRATES_IO_TOKEN }}"
        if: steps.release.outputs.release_created
