---
"on":
  push:
    tags:
      - v*

name: Publish a new release
jobs:
  test_offline:
    name: Offline tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1.3.0
        with:
          sharedKey: cache
      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: "--package xtask -- test --offline"
  cargo_publish:
    needs: test_offline
    name: Publish to cargo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1.3.0
        with:
          sharedKey: cache
      - run: cargo publish -p plex-api
        env:
          CARGO_REGISTRY_TOKEN: "${{ secrets.CRATES_IO_TOKEN }}"
