# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on: push

name: Test authenticated

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Prepare env
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: run -p tools-bootstrap-plex -- --authenticated

      - name: Test against real server [anonymous]
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: test --manifest-path plex-api/Cargo.toml --features 'test_connect_authenticated'
