# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on:
  schedule:
    - cron: '0 0 1 * *'

name: Check for new attributes

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        plex_server_version:
          - latest
          - 1.16.6.1592-b9d49bdb7
          - 1.13.9.5456-ecd600442
          - 1.10.1.4602-f54242b6b
    env:
      X_PLEX_CLIENT_IDENTIFIER: ${{ secrets.X_PLEX_CLIENT_IDENTIFIER }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Cache cargo registry
        uses: actions/cache@v1
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-registry-

      - name: Cache cargo index
        uses: actions/cache@v1
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-index-

      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-test-online-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-build-target-test-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo-build-target-test-online-
            ${{ runner.os }}-cargo-build-target-test-
            ${{ runner.os }}-cargo-build-target-

      - name: Run Plex Server
        run: docker run -d --network=host -e TZ=UTC plexinc/pms-docker:${{ matrix.plex_server_version }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Build plex-cli binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p plex-cli

      - name: Wait for plex-server to boot
        run: target/debug/plex-cli wait --timeout 120 --server-url http://127.0.0.1:32400 -s

      - name: Test against real server [anonymous]
        uses: actions-rs/cargo@v1
        env:
          PLEX_API_SERVER_URL: http://127.0.0.1:32400
        with:
          command: test
          args: --manifest-path plex-api/Cargo.toml --features 'test_new_attributes,test_connect_anonymous'
