# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on:
  schedule:
    - cron: '0 0 1 * *'

name: Check for new attributes

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Wait for plex-server to boot
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p plex-cli wait --server-url http://127.0.0.1:32400 -s

      - name: Test against real server [anonymous]
        uses: actions-rs/cargo@v1
        env:
          PLEX_API_SERVER_URL: http://127.0.0.1:32400
        with:
          command: test
          args: --manifest-path plex-api/Cargo.toml --features 'test_new_attributes,test_connect_anonymous'

    services:
      plex:
        image: plexinc/pms-docker
        ports:
          - 32400:32400
        env:
          TZ: UTC
