# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on:
  schedule:
    - cron: '0 0 1 * *'

name: Check for new attributes

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v1

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Prepare env
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p plex-cli -- --authenticated

      - name: Test against real server
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path plex-api/Cargo.toml --features 'test_new_attributes,test_connect_authenticated,test_connect_anonymous'
